### PR TITLE
Problem: DHT22 sends minus 0 degree as sign-mag

### PR DESCRIPTION
**Pull request by argltuc**
Problem is related to #52 

Solution:
Since all negative temperatures of DHT22 are send in two's complement, it is possible to detect sign-magnitude values and to catch if sensor outputs 0x8000 for a temperature lower then 0°C but higher then -0.1°C

### CODE REVIEW

**Comment by RobTillaart** [comment]
Looks good

**Comment by argltuc** [comment]
uh, I forgott to ingrease version numbers in library.json and library.properties. sorry...

**Comment by RobTillaart** [comment]
No problem, didn't notice either only after merging :)

**Comment by RobTillaart** [comment]
0.4.5 released

**Comment by Anrijs** [comment]
Instead of setting temperature to 0, it should invert sign and 0x80 should be removed from `_bits[2]`.
This works for me:
`
int16_t t = ((_bits[2] & 0x7F) * 256 + _bits[3]);
if(_bits[2] == 0x80)
  _temperature = t * -0.1; 
else
  _temperature = t * 0.1; 
`

**Pull request merged**
